# Generated by Django 3.2.4 on 2021-10-24 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_rename_order_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*')]),
        ),
    ]
